Update ci.yml

diff --git a/Workflows/ci.yml b/Workflows/ci.yml
--- a/Workflows/ci.yml
+++ b/Workflows/ci.yml
@@ -17,12 +17,21 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
+    - name: Log YOUTUBE_API_KEY
+      run: echo "YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}"
+
     - name: Inject API keys
       run: |
         echo "Injecting API keys into HTML file"
         sed -i 's/YOUR_ACCESS_TOKEN/${{ secrets.FACEBOOK_ACCESS_TOKEN }}/g' index.html
         sed -i 's/YOUR_PAGE_ID/${{ secrets.FACEBOOK_PAGE_ID }}/g' index.html
         sed -i 's/REPLACE_WITH_API_KEY/${{ secrets.YOUTUBE_API_KEY }}/g' index.html
+
+    - name: Debug inject
+      run: |
+        grep 'YOUR_ACCESS_TOKEN' index.html || echo "FACEBOOK_ACCESS_TOKEN not found"
+        grep 'YOUR_PAGE_ID' index.html || echo "FACEBOOK_PAGE_ID not found"
+        grep 'REPLACE_WITH_API_KEY' index.html || echo "YOUTUBE_API_KEY not found"
 
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
